/******************
 * Exam 3 Chaining
 *
 * Do not edit this file
 * Instead, edit chain.js
 *
 * chain.js should not use any classes or inheritance
 * only rely on 'this'
 *
 * chain.js can be done cleanly in 20 lines of code, but that is not a requirement
 *
 */

const chain = require('./chain');

console.log(chain.result()); // 0
console.log(chain.one().result()); // 1
console.log(chain.result()); // 0
console.log(chain.two().result()); // 2
console.log(chain.one().one().result()); // 2
console.log(chain.one().two().result()); // 3
console.log(chain.one().one().one().two().one().result()); // 6


