/***********************
 * Exam 3, Inheritance
 *
 * Do not edit this file
 * Instead change constructor.js, es6Class.js, basis.js, and brute.js
 */

const Constructor = require('./constructor');
const fromConstructor = new Constructor('cat');
console.log(fromConstructor.word); // outputs the passed word: 'cat'
// getWord() is an inherited method
console.log(fromConstructor.getWord()); // outputs the passed word, in this case 'cat'

const Es6Class = require('./es6class');
const fromEs6 = new Es6Class('cat');
console.log(fromEs6.word); // outputs the passed word: 'cat'
// getWord() is an inherited method
console.log(fromEs6.getWord()); // outputs the passed word, in this case 'cat'

const basis = require('./basis');
const fromObjCreate = Object.create(basis);
// init() is an inherited method
fromObjCreate.init('cat');
console.log(fromObjCreate.word); // outputs the passed word: 'cat'
// getWord() is an inherited method
console.log(fromObjCreate.getWord()); // outputs the passed word, in this case 'cat'

const bruteForce = require('./brute');
const fromBruteForce = {};
bruteForce(fromBruteForce, basis); // Yes, same 'basis' as above
// init() is an inherited method
fromBruteForce.init('cat');
console.log(fromBruteForce.word); // outputs the passed word: 'cat'
// getWord() is an inherited method
console.log(fromBruteForce.getWord()); // outputs the passed word, in this case 'cat'

